### ISSUE TITLE
Cache of version 2022 does not work since 2023 has been released

### ISSUE THREAD

**Issue by jagot** [teatimeguest/setup-texlive-action#248] opened 2023-03-21 14:57 UTC
I noticed my builds stopped working:

https://github.com/attoyss2023/attoyss2023.github.io/actions/runs/4480159595/jobs/7875071678#step:4:43

Even if I fix to version 2022, it does not work if the artefacts are cached. With `cache: false`, it seems to work: https://github.com/attoyss2023/attoyss2023.github.io/actions/runs/4480467785 but the build times are obviously increased.

**Comment by teatimeguest** [comment] 2023-03-21 18:20
Thank you for reporting the issue!

> I noticed my builds stopped working:
>
> https://github.com/attoyss2023/attoyss2023.github.io/actions/runs/4480159595/jobs/7875071678#step:4:43

This problem seems to be caused by the fact that the CTAN mirrors have not yet completed synchronisation against the new version release. If you re-run the workflow after a while, it should work correctly.

> Even if I fix to version 2022, it does not work if the artefacts are cached.

This is caused by the action not properly handling cache when a new version is released. I will try to fix this issue as soon as possible. Sorry for the inconvenience and thank you for your patience.

**Comment by muzimuzhi** [comment] 2023-03-22 00:36
I tried to add support for texlive 2023 myself, in my fork commit https://github.com/muzimuzhi/setup-texlive-action/commit/41f7580b80c58d4772f367efcc6276be15d9489b.  When testing against this change in https://github.com/muzimuzhi/hello-github-actions/pull/8, tests failed yesterday but just now they passed.

**Comment by teatimeguest** [comment] 2023-03-22 04:18
@muzimuzhi The hard-coded version number is not a problem, as the latest version is also [checked using the CTAN API](https://github.com/teatimeguest/setup-texlive-action/blob/352317d21928f5a5191cfb9bb19410eb5eb28fdb/src/texlive/version.ts#L60-L67). I think the delay between release and sync is the crux of this issue, but I have no idea of an effective workaround for it.

Nevertheless, the commit muzimuzhi@41f7580 is great and appropriate to formally support TeX Live 2023, so PR is very welcome.

**Comment by muzimuzhi** [comment] 2023-03-22 05:29
> I think the delay between release and sync is the crux of this issue, but I have no idea of an effective workaround for it.

CTAN has a master host (https://ctan.org/mirrors, right column) and every mirror is set to [sync with it](https://ctan.org/mirrors/register/).  Perhaps in the first few days of a new texlive release, the master host can be used as a fallback, if the auto chosen CTAN mirror is not in sync yet.

**Comment by teatimeguest** [comment] 2023-03-24 02:02
I have released [v2.6.0](https://github.com/teatimeguest/setup-texlive-action/releases/tag/v2.6.0) for this issue.

- The problem related to sync of mirrors has been mostly resolved, as [most mirrors have completed sync at this moment](https://ctan.org/mirrors/mirmon). This release only adds more user-friendly error messages for this problem, but I am considering incorporating @muzimuzhi's idea into future releases.
- The cache-related problem should be resolved in this release, and now `version: 2022` should work with an existing cache. If you notice that there are still glitches, feel free to re-open the issue.

**Closed by teatimeguest** 2023-03-24 02:02 UTC
Labels: bug
